docs/AboutUs.md

yi hao change to AboutUs.md

---

src/main/java/Util/CommandListPrinter.java
src/main/java/Util/DateTimeFormatTool.java
src/main/java/Util/DateTimeFormatterUtil.java
src/main/java/Util/IntegerChecker.java
src/main/java/Util/StudentFileHandler.java
src/main/java/Util/UI.java
src/main/java/commandHandler/CommandFactory.java
src/main/java/task/Consultation.java
src/main/java/task/Deadline.java
src/main/java/task/Event.java
src/main/java/taskCommands/DeleteCommand.java
src/main/java/taskCommands/MarkCommand.java
src/main/java/taskCommands/UnmarkCommand.java
src/test/java/task/TodoTest.java

Added JUnit Test for Todo Class. Changed util package name to 'Util' to ensure successful import.

JUnit Test for Todo Class

---

src/main/java/commandHandler/CommandFactory.java
src/main/java/commandHandler/CommandHandler.java
src/main/java/commandHandler/CommandParser.java
src/main/java/task/Consultation.java
src/main/java/task/Deadline.java
src/main/java/task/Event.java
src/main/java/task/TaskList.java
src/main/java/task/TaskType.java
src/main/java/taskCommands/ConsultationCommand.java
src/main/java/taskCommands/DeadlineCommand.java
src/main/java/taskCommands/EventCommand.java
src/test/java/taskCommands/EventCommandTest.java

Added DateTime checker for deadline, event and consultation.
Changed input method for tasks from: todo, deadline, event, consultation to: add -pt, add -pd, add -pe, add -c

Implement task management function with DateTime format checker

---

src/main/java/commandHandler/CommandFactory.java
src/main/java/taskCommands/CommandList.java
src/main/java/taskCommands/DeleteTaskCommand.java
src/main/java/taskCommands/FindTaskCommand.java
src/main/java/taskCommands/ListTaskCommand.java
src/main/java/taskCommands/MarkTaskCommand.java
src/main/java/taskCommands/RenameTaskCommand.java
src/main/java/taskCommands/UnmarkTaskCommand.java

Resolves #18 
Edited methods to call task related commands that may also shared with other lists: delete, list, mark, unmark, rename, find. 
format /<COMMAND NAME> -p <COMMAND DETAIL>

Edit taskCommands method in command factory

---

src/main/java/commandHandler/CommandFactory.java
src/main/java/studentcommands/ChangeRemarkCommand.java
src/main/java/studentcommands/DeleteStudentCommand.java
src/main/java/studentcommands/FindStudentCommand.java

The ChangeRemarkCommand, FindStudentCommand, and DeleteStudentCommand classes lack runtime monitoring and validation, making debugging and development challenging.
Let's add logging to track execution flow and capture runtime information for debugging. Use assertions to validate preconditions and invariants during development, ensuring the program is in a valid state.
This improves code robustness, maintainability, and debuggability. Refer to the Java Logging API for best practices.

studentcommand classes: Add logging and assertions

---

src/main/java/commandHandler/CommandFactory.java
src/main/java/studentcommands/ListStudentCommand.java

Added the ListStudentCommand to allow displaying all students in the StudentList. This command retrieves the student list, checks if it is empty, and prints all students if available.
Key changes:
- Implemented logging at different levels (INFO for execution steps, SEVERE for errors).
- Added handling for an empty student list to provide appropriate feedback.
- Ensured the command executes safely with error handling to prevent unexpected failures.
This update improves visibility into the command execution process and ensures better error handling when listing students.

studentCommands/ListStudentCommand: Implement student listing with logging

---

data/tasklist.txt
src/main/java/FileHandlers/TaskListFileLoader.java
src/main/java/FileHandlers/TaskListFileSaver.java
src/main/java/FileHandlers/TaskParser.java
src/main/java/task/TaskList.java
src/main/java/task/Todo.java

Added TaskListFileSaver, TaskListFIleLoader, TaskParser.
Edited TaskList class to load and save from the data file.

Add file handling method for tasklist

---

src/main/java/TASync.java
src/main/java/commandHandler/CommandFactory.java
src/main/java/exception/TASyncException.java
src/main/java/students/Student.java
src/main/java/tutorialCommands/ListTutorialStudentsCommand.java
src/main/java/tutorialCommands/ListUpcomingTutorialsCommand.java

added list tutorial students and list future tutorial sessions

Tutorial class commands

---

src/main/java/TASync.java
src/main/java/commandHandler/CommandFactory.java
src/main/java/commandHandler/CommandHandler.java
src/main/java/taskCommands/CommandList.java

- Implemented HelpCommand to provide users with a list of available commands and their usage.
- Ensured clear and concise formatting for better readability.
- Improved user experience by making it easier to access command information.

Add HelpCommand to display available commands

---

docs/DeveloperGuide.md

- Added ChangeRemarkCommand documentation under studentcommands
- Included implementation overview
- Structured command package breakdown for clarity
This update improves the Developer Guide by providing detailed insights into specific commands.

docs: Update Developer Guide with command package details

---

META-INF/MANIFEST.MF
src/main/java/TASync.java
src/main/java/task/Consultation.java
src/main/java/task/Deadline.java
src/main/java/task/Event.java
src/main/java/tutorial/TutorialClass.java
src/main/java/util/DailySchedule.java
src/main/java/util/UI.java

Resolves #65 
Add check isToday method for event, consultation, deadline and tutorial class
Add UI function to print the daily schedule
Add calling method for daily schedule in main

Add time-tabling feature

---

src/main/java/TASync.java
src/main/java/login/LoginHandler.java
src/main/java/util/UI.java

modified condition used for login to utilise method in TAlogin

add prompt for login menu, utilise method created in main to check password

---

data/PasswordHolder.txt
src/main/java/TASync.java
src/main/java/filehandlers/TALoginFileLoader.java
src/main/java/login/LoginHandler.java
src/main/java/util/UI.java

make password more secure
make main more OOP

31march xb

---

data/tasklist.txt
src/main/java/command/tutorialcommands/NewTutorialCommand.java
src/test/java/studentcommands/ChangeRemarkCommandTest.java
src/test/java/studentcommands/CheckRemarkCommandTest.java
src/test/java/studentcommands/DeleteStudentCommandTest.java
src/test/java/studentcommands/FindStudentCommandTest.java
src/test/java/studentcommands/NewStudentCommandTest.java
src/test/java/studentcommands/utils/StudentCommandTestUtil.java

- Abstract setUp code for each test in order to reduce code duplication
- Create ChangeRemarkCommandTest, CheckRemarkCommandTest, DeleteStudentCommandTest,FindStudentCommandTest and NewStudentCommandTest for easy testing of methods

Add tests for more studentcommands

---

docs/DeveloperGuide.md

Update developer guide for task commands

---

docs/team/samstt.md

- Add summary of contributions to the project that involves details on what certain commands do and the justification for them
- Add details on project management of TASync
- Add contributions to documentation of UG and DG
- Add other additional details to paint a clearer picture of my contributions

Update PPP for XiaoNa

---

docs/DeveloperGuide.md

- Add task commands with implementation details and operations

Update the DG with tutorial commands

---

docs/DeveloperGuide.md

- Add user stories that inspired the features of TASync

Update the DG with user stories

---

docs/UserGuide.md

Update user guide with introduction and quick start

---

docs/DeveloperGuide.md
docs/diagrams/CommandHandlingComponent.puml
docs/diagrams/DataManagementComponentClassDiagram.puml
docs/diagrams/OverallClassDiagram.puml
docs/diagrams/SimplifiedOverallClassDiagram.puml

- Add class diagram for data management component of TASync
- Add class diagram for command handling component of TASync

Add Class Diagrams
